#!/bin/bash
# HASHBANG OR SHEBANG -> UNIX TO RUN SCRIPT INTO BIN/BASH shell
# CHECK AND/OR INSTALL FFMPEG
sudo apt install ffmpeg
# ENABLE PERMISSION
sudo chmod +x ffmpeg_script.sh
# CREATE THE DIRECTORY FOR THE COMPRESSED MP4's.
mkdir output;
# RUNNING THE SCRIPT: IN THE FILE YOU'RE IN 
# FOR EACH MP4's IN THE FILE COMPRESS MP4 AND OUTPUT TO A NEW DIRECTORY.
for file in ./*.mp4; do ffmpeg -i $file -vcodec h264 -acodec mp3 output/$file; done
# CREATE THE DIRECTORY FOR THE WEBM FILES.
mkdir webm;
# FOR EACH MP4 IN THE FILE CONVERT TO WEBM AND PLACE IT INTO THE NEW DIRECTORY.
for file in ./*.mp4; do ffmpeg -i $file -vcodec libvpx -acodec libvorbis "webm/${file%%.mp4}.webm"; done

# THIS SCRIPT MAKES CONVERSION OF A BUNCH OF VIDEOS (MP4'S) TO PREPARE FOR WEB USAGE(S):

#CREATING SIMPLIFIED AND COMPRESSED VIDEOS & PROVIDE WEBM OF THE SAME VIDEO TO USE IN WEB-APPLICATIONS.

#TUTORIAL:
# CREATE OR PLACE MP4's IN A PARTICLE FILE.
# IN THE SAME FILE OF THE MP4'S RUN THE SCRIPT :  ./FFMPEG_SCRIPT.SH 
# SUDO IS USED THEREFORE USE YOUR PASSWORD TO CONTINUE.
# PROCESS
# * * COMPLETE* * 